# Generated by Django 5.1.2 on 2025-08-12 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('breed', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='pets/')),
                ('status', models.CharField(choices=[('available', 'Available'), ('lost', 'Lost'), ('found', 'Found'), ('rescued', 'Rescued')], default='available', max_length=10)),
            ],
        ),
    ]
