# Generated by Django 5.1.2 on 2025-08-24 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='breed',
            new_name='species',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='status',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='type',
        ),
        migrations.AddField(
            model_name='pet',
            name='age',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pet',
            name='image',
            field=models.ImageField(upload_to='pet_images/'),
        ),
    ]
