# Generated by Django 5.1.2 on 2025-08-24 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_rename_breed_pet_species_remove_pet_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('lost', 'Lost'), ('found', 'Found'), ('rescued', 'Rescued')], default='available', max_length=10),
        ),
    ]
