# Generated by Django 5.1.2 on 2025-09-06 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_pet_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
